#!/usr/bin/env bash
ip_addr=$(ip -f inet addr show enp0s3 | grep inet | awk '{ print $2 }' | cut -d'/' -f1)
if [[ ! -d $PWD/venv ]]; then
    python3 -m virtualenv $PWD/venv
    source $PWD/venv/bin/activate
    pip install -r $PWD/requirements.txt
    deactivate
fi

source $PWD/venv/bin/activate
jupyter notebook --ip $ip_addr --port 1337 --no-browser
deactivate
